# Generate data-raw/theme-data/numbers.yml from the Apple Numbers chart
# palettes extracted by data-raw/reference/numbers/fetch.sh.
#
# Stage 2 of 2. Run fetch.sh first; this script reads only the persisted
# files under data-raw/reference/numbers, never /Applications.
suppressPackageStartupMessages({
  library("purrr")
  library("jsonlite")
  library("yaml")
})

ref_dir <- here::here("data-raw", "reference", "numbers")
plist_dir <- file.path(ref_dir, "plists")

if (!dir.exists(plist_dir)) {
  stop(
    "No extracted palettes found at ",
    plist_dir,
    ".\n",
    "Run data-raw/reference/numbers/fetch.sh first (needs macOS with Numbers installed)."
  )
}

# Within a palette the 2D area, bar, column and pie fills carry identical
# series colors, so one property is enough. Verified in check_variants_agree().
fill_properties <- c(
  "SFC2DAreaFillProperty",
  "SFC2DBarFillProperty",
  "SFC2DColumnFillProperty",
  "SFC2DPieFillProperty"
)

n_series <- 6L

as_hex <- function(r, g, b) {
  grDevices::rgb(r, g, b, maxColorValue = 1)
}

#' Convert the device-CMYK colors through ColorSync in a single call
#'
#' A naive `1 - x` conversion is materially wrong for these: Numbers' "Blue"
#' series 1 is #5E86B8 through ColorSync but #5EA3FF naively.
cmyk_to_srgb <- function(cmyk) {
  if (!length(cmyk)) {
    return(character(0))
  }
  script <- file.path(ref_dir, "cmyk-to-srgb.swift")
  input <- map_chr(cmyk, ~ paste(format(.x, digits = 17), collapse = " "))
  out <- system2("swift", shQuote(script), input = input, stdout = TRUE)
  if (length(out) != length(cmyk)) {
    stop("cmyk-to-srgb.swift returned ", length(out), " colors for ", length(cmyk), " inputs.")
  }
  out
}

#' Pull the six series colors out of one fill property, deferring CMYK
#'
#' Returns a list with the colors resolved so far (NA where a CMYK conversion
#' is still pending) plus the CMYK quadruples needing conversion.
read_series <- function(fills) {
  colors <- rep(NA_character_, n_series)
  pending <- list()

  for (i in seq_len(n_series)) {
    series <- fills[[paste0("Series_", i - 1L)]]
    type <- series[["color-type"]]
    if (type %in% c("calibrated-rgb", "srgb")) {
      colors[[i]] <- as_hex(series$r %||% 0, series$g %||% 0, series$b %||% 0)
    } else if (type %in% c("calibrated-white", "device-gray")) {
      w <- series$w %||% series$g %||% 0
      colors[[i]] <- as_hex(w, w, w)
    } else if (type == "device-cmyk") {
      pending[[as.character(i)]] <- c(
        series$c %||% 0,
        series$m %||% 0,
        series$y %||% 0,
        series$k %||% 0
      )
    } else {
      stop("Unhandled color-type: ", type)
    }
  }
  list(colors = colors, pending = pending)
}

`%||%` <- function(a, b) if (!is.null(a)) a else b

#' Guard the assumption that lets us keep one vector per palette
check_variants_agree <- function(fills, palette) {
  variants <- map(fill_properties, ~ read_series(fills[[.x]]))
  reference <- variants[[1]]
  for (v in variants[-1]) {
    if (!identical(v$colors, reference$colors) || !identical(v$pending, reference$pending)) {
      stop(
        "Palette '",
        palette,
        "' has different series colors across 2D chart types; ",
        "the one-vector-per-palette assumption no longer holds."
      )
    }
  }
  reference
}

# Apple's own display names, kept verbatim so that numbers_pal("Mid Century")
# matches what the user sees in the Numbers interface.
files <- sort(list.files(plist_dir, pattern = "\\.json$", full.names = TRUE))
palette_names <- sub("\\.json$", "", basename(files))

parsed <- map(files, function(f) {
  fills <- fromJSON(f, simplifyVector = FALSE)$fills
  check_variants_agree(fills, sub("\\.json$", "", basename(f)))
})
names(parsed) <- palette_names

# Convert every deferred CMYK color in one shell-out rather than one per color.
all_pending <- unlist(map(parsed, "pending"), recursive = FALSE, use.names = FALSE)
converted <- cmyk_to_srgb(all_pending)

cursor <- 0L
palettes <- imap(parsed, function(p, palette) {
  colors <- p$colors
  for (idx in names(p$pending)) {
    cursor <<- cursor + 1L
    colors[[as.integer(idx)]] <- converted[[cursor]]
  }
  if (anyNA(colors)) {
    stop("Palette '", palette, "' has unresolved colors.")
  }
  map(seq_along(colors), ~ list(name = paste0("Series ", .x), value = colors[[.x]]))
})

out_path <- here::here("data-raw", "theme-data", "numbers.yml")
version <- readLines(file.path(ref_dir, "VERSION"), warn = FALSE)[[1]]

writeLines(
  c(
    paste0("# Apple Numbers ", version, " chart palettes."),
    "# Generated by data-raw/numbers_palettes.R -- do not edit by hand.",
    "# See data-raw/reference/numbers/SOURCES.md.",
    as.yaml(palettes)
  ),
  out_path
)

message("Wrote ", length(palettes), " palettes to ", out_path)
